### ISSUE TITLE
Animations for tabs on change?

### ISSUE THREAD

**Issue by Chinese1904** [cristijora/vue-form-wizard#56]
Last but not least, I do have one more question. Haha

Has anyone tried to accomplish tab animations? Just simple fade in and out animations of the actual `.wizard-tab-content` ?

I think those would look great! :-)

**Comment by cristijora** [comment]
Hey @Chinese1904 This unfortunately is not possible now unless you use vue-router 
https://jsfiddle.net/bt5dhqtf/267/

I started working on an upgraded version (more internally) which will allow transitions for the content

**Comment by cristijora** [comment]
Hi again @Chinese1904 

Coming with an update here.
You could use simple css animations on `tab-containers`
Here is an example with animate.css
https://jsfiddle.net/bt5dhqtf/1477/

```css

.wizard-tab-content {
  .wizard-tab-container {
    display: block;
    animation: fadeInRight 0.3s;
  }
}

```
